import 'package:api_riot/models/champion.dart';

class BigData {
  List<String> datadata = [
    "Aatrox",
    "Ekko",
    "Jinx",
    "Miss Fortune",
    "Shen",
    "Varus",
    "Ahri",
    "Elise",
    "Kalista",
    "Mordekaiser",
    "Shyvana",
    "Vayne",
    "Akali",
    "Evelynn",
    "Karma",
    "Morgana",
    "Singed",
    "Veigar",
    "Alistar",
    "Ezreal",
    "Karthus",
    "Nami",
    "Sion",
    "Vel’Koz",
    "Amumu",
    "Fiddlesticks",
    "Kassadin",
    "Nasus",
    "Sivir",
    "Vi",
    "Anivia",
    "Fiora",
    "Katarina",
    "Nautilus",
    "Skarner",
    "Viktor",
    "Annie",
    "Fizz",
    "Kayle",
    "Nidalee",
    "Sona",
    "Vladimir",
    "Ashe",
    "Galio",
    "Kennen",
    "Nocturne",
    "Soraka",
    "Volibear",
    "Aurelion Sol ",
    "Gangplank",
    "Kha’Zix",
    "Nunu",
    "Swain",
    "Warwick",
    "Azir",
    "Garen",
    "Kindred",
    "Olaf",
    "Syndra",
    "Wukong",
    "Bard",
    "Gnar",
    "Kled",
    "Orianna",
    "Tahm Kench",
    "Xerath",
    "Blitzcrank",
    "Gragas",
    "Kog’Maw",
    "Pantheon",
    "Taliyah",
    "Zin Zhao",
    "Brand",
    "Graves",
    "LeBlanc",
    "Poppy",
    "Talon",
    "Yasuo",
    "Braum",
    "Hecarim",
    "Lee Sin",
    "Quinn",
    "Taric",
    "Yorick",
    "Caitlyn",
    "Heimerdinger",
    "Leona",
    "Rammus",
    "Teemo",
    "Zac",
    "Camille",
    "Illaoi",
    "Lissandra",
    "Rek’Sai",
    "Thresh",
    "Zed",
    "Cassiopeia",
    "Irelia",
    "Lucian",
    "Renekton",
    "Tristana",
    "Ziggs",
    "Cho’Gath",
    "Ivern",
    "Lulu",
    "Rengar",
    "Trundle",
    "Zilean",
    "Corki",
    "Janna",
    "Lux",
    "Riven",
    "Tryndamere",
    "Darius",
    "Jarvan IV",
    "Malphite",
    "Rumble",
    "Twisted Fate",
    "Diana",
    "Jax",
    "Malzahar",
    "Ryze" "Twitch",
    "Dr. Mundo",
    "Jayce",
    "Maokai",
    "Sejuani",
    "Udyr",
    "Draven",
    "Jhin",
    "Master Yi",
    "Shaco",
    "Urgot",
  ];

  createData() {
    List<Champion> champ = [];
    for (String name in datadata) {
      champ.add(Champion([], name));
    }
    return champ;
  }
}
